services:
  database:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - database
    environment:
      DB_URL: "mongodb://database:27017/"
      REDIS_URL: "redis://redis:6379"
      SECRET: "123456"
volumes:
  db_data:
